instrumentation:
    root: .
    excludes:
      - '**/public/**'
      - '**/static-routes/**'
      - '**/docsite/**'
      - '**/coverage/**'
    extensions:
      - .js
      - .jsx
    embed-source: true
    include-all-sources: true
