language: node_js
node_js:
  - '6'
notifications:
  slack:
    on_success: change
    secure: HTWyZ6J2aDXGssdTAFh5L5kc86rqbPAtmS9/H0Ux3g3hoIfdmCKCzr3UpHsdXDbUB7yUX0quNmA7Hqeey5apDTUaD8v6TjDs98JhMEKuR96JHRPECeKMjHdicwFLY6AAehsfhqZKDi8nMjPoPtf9H/TcgZ5GvBMJMIZS+m+kXy8=
