
// All actions, used by actions or reducers, go here

export const CLOSE_CARD = 'CLOSE_CARD'
export const LOAD_CARD_PAGE = 'LOAD_CARD_PAGE'
export const NAVIGATE = 'NAVIGATE'
export const OPEN_CARD = 'OPEN_CARD'

export const RECEIVE_ALL_REGIONS = 'RECEIVE_ALL_REGIONS'
export const RECEIVE_CARD_PAGE_DATA = 'RECEIVE_CARD_PAGE_DATA'
export const RECEIVE_CARD_PAGES = 'RECEIVE_CARD_PAGES'
export const RECEIVE_CARD_QUERY = 'RECEIVE_CARD_QUERY'
export const RECEIVE_CHART_DATA = 'RECEIVE_CHART_DATA'
export const RECEIVE_QUERY_RESULT = 'RECEIVE_QUERY_RESULT'
export const RECEIVE_REGION = 'RECEIVE_REGION'
export const RECEIVE_TABLE_HEADERS = 'RECEIVE_TABLE_HEADERS'
export const RECEIVE_TABLES = 'RECEIVE_TABLES'

export const REQUEST_CARD_QUERY = 'REQUEST_CARD_QUERY'
export const REQUEST_CHART_DATA = 'REQUEST_CHART_DATA'
export const REQUEST_REGION = 'REQUEST_REGION'

export const SELECT_DATA_VIEW = 'SELECT_DATA_VIEW'
export const UPDATE_CARD_QUERY = 'UPDATE_CARD_QUERY'
