
// All actions, used by actions or reducers, go here

export const OPEN_CARD = 'OPEN_CARD'
export const CLOSE_CARD = 'CLOSE_CARD'
export const LOAD_CARD_PAGE = 'LOAD_CARD_PAGE'
export const NAVIGATE = 'NAVIGATE'

export const SET_CURRENT_REGION = 'SET_CURRENT_REGION'
export const REGION_NOT_FOUND = 'REGION_NOT_FOUND'

export const SET_CURRENT_CARDS_PAGE = 'SET_CURRENT_CARDS_PAGE'
export const CARD_PAGE_NOT_FOUND = 'CARD_PAGE_NOT_FOUND'
export const CARD_PAGE_TAB_NOT_FOUND = 'CARD_PAGE_TAB_NOT_FOUND'
export const TAB_NOT_FOUND_IN_CARD = 'TAB_NOT_FOUND_IN_CARD'
export const SET_CURRENT_CARD = 'SET_CURRENT_CARD'
export const SET_CURRENT_TAB = 'SET_CURRENT_TAB'

export const CARD_NOT_FOUND_IN_PAGE = 'CARD_NOT_FOUND_IN_PAGE'

export const REQUEST_CARD_QUERY_RESULT = 'REQUEST_CARD_QUERY_RESULT'
export const RECEIVE_CARD_QUERY_RESULT = 'RECEIVE_CARD_QUERY_RESULT'

export const REQUEST_VARIABLE_DEFINITIONS = 'REQUEST_VARIABLE_DEFINITIONS'
export const RECEIVE_VARIABLE_DEFINITIONS = 'RECEIVE_VARIABLE_DEFINITIONS'

export const NO_DATA_FOR_CARD = 'NO_DATA_FOR_CARD'
export const RECEIVE_CARD_PAGE_DATA = 'RECEIVE_CARD_PAGE_DATA'
export const RECEIVE_CARD_QUERY = 'RECEIVE_CARD_QUERY'
export const RECEIVE_QUERY_RESULT = 'RECEIVE_QUERY_RESULT'

export const RECEIVE_HEADER_GROUPS = 'RECEIVE_HEADER_GROUPS'

export const REQUEST_CARD_QUERY = 'REQUEST_CARD_QUERY'

export const REQUEST_REGION_SUMMARY_DATA = 'REQUEST_REGION_SUMMARY_DATA'
export const RECEIVE_REGION_SUMMARY_DATA = 'RECEIVE_REGION_SUMMARY_DATA'
export const NO_SUMMARY_DATA = 'NO_SUMMARY_DATA'
export const REQUEST_REGION = 'REQUEST_REGION'

export const SELECT_DATA_VIEW = 'SELECT_DATA_VIEW'
export const UPDATE_CARD_QUERY = 'UPDATE_CARD_QUERY'

export const GOOGLE_TAG_MANAGER_EVENT = 'GOOGLE_TAG_MANAGER_EVENT'
