// All actions, used by actions or reducers, go here
export const NAVIGATE = 'NAVIGATE'

export const CLOSE_CARD = 'CLOSE_CARD'
export const OPEN_CARD = 'OPEN_CARD'

export const SET_CURRENT_REGION = 'SET_CURRENT_REGION'
export const REGION_NOT_FOUND = 'REGION_NOT_FOUND'

export const REQUEST_REGION_SUMMARY_QUERY = 'REQUEST_REGION_SUMMARY_QUERY'
export const RECEIVE_REGION_SUMMARY_QUERY = 'RECEIVE_REGION_SUMMARY_QUERY'

export const RECEIVE_CHART_DATA = 'RECEIVE_CHART_DATA'
export const RECEIVE_QUERY_RESULT = 'RECEIVE_QUERY_RESULT'

export const SET_CARD_PAGE = 'SET_CARD_PAGE'
export const REQUEST_CARD_QUERY = 'REQUEST_CARD_QUERY'
export const REQUEST_CHART_DATA = 'REQUEST_CHART_DATA'
export const REQUEST_REGION = 'REQUEST_REGION'

export const SELECT_DATA_VIEW = 'SELECT_DATA_VIEW'
export const UPDATE_CARD_QUERY = 'UPDATE_CARD_QUERY'
